<?php

namespace Kf2Exp\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AchievementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchievementRepository extends EntityRepository{

  public function getMapsList() {
    $qb = $this->createQueryBuilder('a');
    $qb->select('a')
            ->where('a.enabled = 1')
            ->andWhere('a.achievementMap = 1')
            ->orderBy('a.mapName', 'ASC');

    $achievementMaps = $qb->getQuery()
            ->getResult();

    $results = array();

    foreach ($achievementMaps as $achievementMap)
    {
      if (array_key_exists($achievementMap->getMapName(), $results) == false)
      {
        $results[$achievementMap->getMapName()] = array();
      }
    }

    foreach ($achievementMaps as $achievementMap)
    {
      $results[$achievementMap->getMapName()][$achievementMap->getDifficulty()] = $achievementMap->getAchievementName();
    }

    return $results;
  }

}
