<?php

namespace Kf2Exp\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerStatRepository extends EntityRepository{

  public function getStatsRanking($statName) {
    $qb = $this->createQueryBuilder('ps');
    $qb->select('ps')
            ->leftJoin('ps.stat', 's')
            ->leftJoin('ps.player', 'p')
            ->leftJoin('p.country', 'c')
            ->where('s.statName = :s_stat_name')
            ->setParameter('s_stat_name', $statName)
            ->orderBy('ps.value', 'DESC');

    $playersStats = $qb->getQuery()
            ->getResult();

    $array = array();

    foreach ($playersStats as $playersStat)
    {
      if (null === $playersStat->getPlayer()->getCountry()) {
        $country = null;
      } else {
      	$country = $playersStat->getPlayer()->getCountry()->getCountryName();
      }

      $array[] = array(
        'playerId' => $playersStat->getPlayer()->getId(),
        'steamId' => $playersStat->getPlayer()->getSteamId(),
        'steamName' => $playersStat->getPlayer()->getSteamName(),
        'value' => number_format($playersStat->getValue()),
        'country' => $country,
        'timePlayed' => $playersStat->getPlayer()->getTimePlayed()
      );
    }

    return $array;
  }
}
