<?php

namespace Kf2Exp\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerStatRepository extends EntityRepository{

  public function getStatsRanking($statName, $nbPlayerLoaded, $nbPlayerToLoad) {
    $qb = $this->createQueryBuilder('ps');
    $qb->select('ps')
            ->leftJoin('ps.stat', 's')
            ->where('s.statName = :s_stat_name')
            ->setParameter('s_stat_name', $statName)
            ->setMaxResults($nbPlayerToLoad)
            ->setFirstResult($nbPlayerLoaded)
            ->orderBy('ps.value', 'DESC');

    $playersStats = $qb->getQuery()
            ->getResult();

    $array = array();

    foreach ($playersStats as $playersStat)
    {
      $array[] = array(
          'playerId' => $playersStat->getPlayer()->getId(),
          'steamId' => $playersStat->getPlayer()->getSteamId(),
          'steamName' => $playersStat->getPlayer()->getSteamName(),
          'value' => number_format($playersStat->getValue()));
    }

    return $array;
  }

}
