<?php

namespace Kf2Exp\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatRepository extends EntityRepository{

  public function findAllOrderedByVisibleName() {
    return $this->getEntityManager()
                    ->createQuery(
                            "SELECT s FROM Kf2ExpAppBundle:Stat s WHERE s.enabled = '1' ORDER BY s.visibleStatName ASC"
                    )
                    ->getResult();
  }

}
