services:
  kf2exp.steamrequestmanager:
    class: Kf2Exp\AppBundle\Services\SteamRequestManager\SteamRequestManager
    arguments: [ "@doctrine.orm.entity_manager", "%kernel.root_dir%", "%steam_api_key%", "%max_request%", "%player_cache_seconds%"]