<?php

namespace Kf2Exp\AppBundle\Repository;

/**
 * PerkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerkRepository extends \Doctrine\ORM\EntityRepository
{
}
